CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE Livro (
    ISBN INT PRIMARY KEY,
    Titulo VARCHAR(50),
    AnoDePublicacao INT
);

CREATE TABLE Autor (
    AutorID INT PRIMARY KEY,
    Nome VARCHAR(255),
    DataDeNascimento DATE,
    Nacionalidade VARCHAR(50)
);

CREATE TABLE Usuario (
    UsuarioID INT PRIMARY KEY,
    Nome VARCHAR(50),
    Endereco VARCHAR(255)
);

CREATE TABLE EMPRESTIMO (
    IDdeSAIDA INT PRIMARY KEY,
    DATAdeSAIDA DATE,
    PREVISAOdeCHEGADA DATE,
    UsuarioID INT,
    FOREIGN KEY (UsuarioID) REFERENCES Usuario(UsuarioID)
);

CREATE TABLE DEVOLUCAO (
    IDdeCHEGADA INT PRIMARY KEY,
    DATEdeCHEGADA DATE,
    MULTA INT
);    

CREATE TABLE LIVROAUTOR (
    ISBN INT,
    AutorID INT,
    PRIMARY KEY(ISBN, AutorID),
    FOREIGN KEY (ISBN) REFERENCES Livro(ISBN),
    FOREIGN KEY (AutorID) REFERENCES Autor(AutorID)
);

CREATE TABLE LivroEMPRESTIMO (
    ISBN INT,
    IDdeEmprestimo INT,
    PRIMARY KEY(ISBN, IDdeEmprestimo),
    FOREIGN KEY (ISBN) REFERENCES Livro(ISBN),
    FOREIGN KEY (IDdeEmprestimo) REFERENCES EMPRESTIMO(IDdeSAIDA)
);
