CREATE DATABASE BlogDB;
USE BlogDB;

CREATE TABLE AUTOR(
	AUTORID INT PRIMARY KEY,
	NOME VARCHAR(50),
	EMAIL VARCHAR(50)
);

CREATE TABLE POST(
    POSTID INT PRIMARY KEY,
    TITULO VARCHAR(50),
    CONTEUDO VARCHAR(255),
    DATAdePUBLICACAO DATE,
    AUTORID INT,
    FOREIGN KEY (AUTORID) REFERENCES AUTOR(AUTORID)
);

	CREATE TABLE COMENTARIO(
	COMENTARIOID INT PRIMARY KEY,
	TEXTOdoCOMENTARIO VARCHAR(255),
	DATAdoCOMENTARIO DATE,
    AUTORID  INT,
    POSTID INT,
    FOREIGN KEY (AUTORID) REFERENCES AUTOR(AUTORID),
    FOREIGN KEY (POSTID) REFERENCES POST(POSTID)
);