CREATE DATABASE ESTOQUEBD;

USE ESTOQUEBD;

CREATE TABLE PRODUTOS(
	PRODUTOID INT PRIMARY KEY,
    NOMEdoPRODUTO VARCHAR(255),
	PRECO INT,
	QUANTIDADEemESTOQUE INT
);

INSERT INTO PRODUTOS (PRODUTOID, NOMEdoPRODUTO, PRECO, QUANTIDADEemESTOQUE)
VALUES (1, 'SMARTPHONE', 799.99, 20);
INSERT INTO PRODUTOS (PRODUTOID, NOMEdoPRODUTO,PRECO,QUANTIDADEemESTOQUE)
VALUES (2,'TABLET',249.99,10);
INSERT INTO PRODUTOS (PRODUTOID, NOMEdoPRODUTO,PRECO,QUANTIDADEemESTOQUE)
VALUES (3,'FONE DE OUVIDO', 49.99, 50);

SHOW TABLES;
SHOW COLUMNS FROM PRODUTOS;
SELECT * FROM PRODUTOS;



UPDATE PRODUTOS
SET QUANTIDADEemESTOQUE = 25
WHERE PRODUTOID = 1;

UPDATE produtos
SET QUANTIDADEemESTOQUE = QUANTIDADEemESTOQUE - 5
WHERE PRODUTOID = 2;

UPDATE produtos 
SET QUANTIDADEemESTOQUE = QUANTIDADEemESTOQUE - 10
WHERE PRODUTOID = 3;

-- CASO O NUMERO DE ESTOQUE ESTEJA EM 0
DELETE FROM PRODUTOS
WHERE QUANTIDADEemESTOQUE <= 0; 

