CREATE DATABASE TECHDATA;

USE TECHDATA;

CREATE TABLE USUARIOS(
	USUARIOSID INT PRIMARY KEY,
    NOMEdeUSUARIO VARCHAR(255)
);    

CREATE TABLE PRODUTOS(
	PRODUTOID INT PRIMARY KEY,
    NOMEdoPRODUTO VARCHAR(255),
	PRECO INT,
	QUANTIDADEemESTOQUE INT
);

CREATE TABLE TRANSACOES(
	TRANSACOESID INT PRIMARY KEY,
	TRANSACOESDATE DATE,
	TRANSACOESVALOR INT
);


-- CONSULTAS

 -- Seleção de dados
SELECT * FROM TRANSACOES;

-- Renomeando colunas
SELECT TRANSACOESID AS ID_Transacao, TRANSACOESDATE AS Data, TRANSACOESVALOR AS Valor FROM TRANSACOES;

-- Filtragem com a cláusula WHERE

SELECT TRANSACOESVALOR AS VALOR FROM TRANSACOES WHERE TRANSACOESVALOR > 100;

--  Ordenação com a cláusula ORDER BY
SELECT TRANSACOESVALOR FROM TRANSACOES ORDER BY TRANSACOESVALOR DESC;

-- Agregação com funções SQL
SELECT AVG(TRANSACOESVALOR) AS média, MAX(TRANSACOESVALOR) AS valor_máximo, MIN(TRANSACOESVALOR) AS valor_minimo, COUNT(*) AS número_total_de_transações FROM TRANSACOES;

-- Agrupamento com a cláusula GROUP BY
SELECT TRANSACOESID AS PRODUTO, AVG(TRANSACOESVALOR) AS MEDIA FROM TRANSACOES GROUP BY TRANSACOESID;

-- Consulta combinada
SELECT PRODUTOID AS Categoria, COUNT(TRANSACOESID) AS QuantidadeTotal, SUM(TRANSACOESVALOR) AS ValorTotalVendas, AVG(TRANSACOESVALOR) AS MediaValorPorTransacao FROM PRODUTOS
JOIN TRANSACOES ON PRODUTOID = TRANSACOESID
GROUP BY PRODUTOID;


